# Generated by Django 4.2.6 on 2023-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drively_app', '0003_user_role_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='token_value',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
