# Generated by Django 4.2.6 on 2023-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drively_app', '0004_remove_user_role_user_token_value_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_value',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
