# Generated by Django 4.2.6 on 2023-10-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drively_app', '0005_alter_user_token_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
