# Generated by Django 4.2.6 on 2023-10-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drively_app', '0006_user_email_token_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
    ]
