# Generated by Django 4.2.6 on 2023-10-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drively_app', '0007_rename_is_verified_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_token',
        ),
    ]
